---
- hosts: controller
  become: yes

  vars_files:
    - ./vars/credentials.yml

  roles:
    - ansible

  tasks:
  - name: generate SSH keys
    user:
      name: "{{ default['user'] }}"
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa

  - name: copy SSH key to node
    command: >
      sshpass -p "{{ default['password'] }}"
      ssh-copy-id -i /home/"{{ default['user'] }}"/.ssh/id_rsa.pub
      -o StrictHostKeyChecking=no "{{ default['user'] }}"@{{ item.ip }}
    with_items:
      - { ip: "192.168.11.3" }
      - { ip: "192.168.11.4" }
      - { ip: "192.168.11.5" }
...
